NDM_DATABASE: ../../data/nlib/image_process_09_chipfinish.nlib
NDM_SEARCH_PATH: 
BLOCK: image_process
MAPPING_FILE: ../../data/techfile/TD-LO40-XS-2037v0/CCI_StarRC_40LL_1P9M_7Ic_2TMc_ALPA2_V1.14_0/CCI_flow/StarRC_40LL_1P9M_7Ic_2TMc_ALPA2_cell.map
GDS_LAYER_MAP_FILE:
REDUCTION: NO_EXTRA_LOOPS
NETS: *
EXTRACTION: RC
DPT: NO
NETLIST_NODE_SECTION: YES
EXTRACT_VIA_CAPS: YES
NUM_CORES: 16
CORNERS_FILE: ./cmin_m40c.smc
SELECTED_CORNERS: CMIN
SIMULTANEOUS_MULTI_CORNER: YES
METAL_FILL_POLYGON_HANDLING: FLOATING

MAGNIFICATION_FACTOR: 0.9
MAGNIFY_DEVICE_PARAMS: NO

COUPLE_TO_GROUND: NO
NETLIST_COMPRESS_COMMAND: gzip -q
COUPLING_ABS_THRESHOLD: 1E-16
COUPLING_REL_THRESHOLD: 0.01
COUPLING_REPORT_NUMBER: 1000000
COUPLING_REPORT_FILE: image_process.coupling.rpt
NETLIST_FORMAT: SPEF
NETLIST_FILE: ./image_process.spef.gz
SUMMARY_FILE: image_process.star_sum
STAR_DIRECTORY: ./CMIN/star


