@REM BLOCK:ISP_top
@REM TOP_DEF_FILE:/home/rocky/Desktop/ASIC_backend/pt/pt_files/ISP_top.def
@REM LEF_FILE:/home/rocky/Desktop/ASIC_backend/scc40nll_8lm_2tm.lef
@REM LEF_FILE:/home/rocky/Desktop/ASIC_backend/SMIC/S40/smic/SCC40NLL_VHSC40_RVT_V0.1/SCC40NLL_VHSC40_RVT_V0p1/lef/macro/scc40nll_vhsc40_rvt_ant.lef
@REM LEF_FILE:/home/rocky/Desktop/ASIC_backend/SMIC/S40/smic/SP40NLLD2RN_3P3V_V0p4/lef/SP40NLLD2RN_3P3V_V0p1_8MT_2TM.lef
@REM LEF_FILE:/home/rocky/Desktop/ASIC_backend/SMIC/SRAM_Lib_2025/RAMTP1024X16/lef/RAMTP1024X16.lef
NDM_DATABASE: ../../data/nlib/image_process_09_chipfinish.nlib
NDM_SEARCH_PATH: 
BLOCK: image_process
MAPPING_FILE: ../../data/techfile/TD-LO40-XS-2037v0/CCI_StarRC_40LL_1P9M_7Ic_2TMc_ALPA2_V1.14_0/CCI_flow/StarRC_40LL_1P9M_7Ic_2TMc_ALPA2_cell.map
GDS_LAYER_MAP_FILE:
REDUCTION: NO_EXTRA_LOOPS
NETS: *
EXTRACTION: RC
DPT: NO
NETLIST_NODE_SECTION: YES
EXTRACT_VIA_CAPS: YES
NUM_CORES: 16
CORNERS_FILE: ./cmin_m40c.smc
SELECTED_CORNERS: CMIN
SIMULTANEOUS_MULTI_CORNER: YES
METAL_FILL_POLYGON_HANDLING: FLOATING

@REM simc arm_pr要求加的两设置
MAGNIFICATION_FACTOR: 0.9
MAGNIFY_DEVICE_PARAMS: NO

COUPLING_TO_GROUND: NO
NETLIST_COMPRESS_COMMAND: gzip -q
COUPLING_ABS_THRESHOLD: 1E-16
COUPLING_REL_THRESHOLD: 0.01
COUPLING_REPORT_NUMBER: 1000000
COUPLING_REPORT_FILE: image_process.coupling.rpt
NETLIST_FORMAT: SPEF
NETLIST_FILE: ./image_process.spef.gz
SUMMARY_FILE: image_process.star_sum
STAR_DIRECTORY: ./CMIN/star


