
LAYOUT ERROR ON INPUT NO

LAYOUT CASE YES
SOURCE CASE YES

LAYOUT PRIMARY "image_icb"
LAYOUT PATH "/home/master/Desktop/04_pv/merge/Calibredrv/top_merge.gds"
LAYOUT SYSTEM GDSII
LAYOUT TEXT FILE "./image_icb.text"

SOURCE PRIMARY "image_icb"
SOURCE PATH "./top.spi"
SOURCE SYSTEM SPICE
LVS ISOLATE SHORTS YES flat //<LVS_REPORT>.shorts
LVS REPORT OPTION S V R F
LVS REPORT "./lvs.rpt"

ERC RESULTS DATABASE "./erc.db" ASCII
ERC SUMMARY REPORT "./erc.rpt" HIER
ERC MAXIMUM RESULTS ALL
ERC MAXIMUM VERTEX ALL

LVS EXECUTE ERC YES
LVS SPICE CULL PRIMITIVE SUBCIRCUITS YES
DRC ICSTATION YES

include ./SMIC_CalLVS_40LL_1125_V1.15_0.lvs






