################################################################
# (C) COPYRIGHT 2010 Apache Design Systems
# ALL RIGHTS RESERVED
#
#
#   $Author: ragarwal $
#   $Date: 2013/06/25 09:03:56 $
#   $Revision: 1.10 $
#   $Id: atclDisplaySigem.tcl,v 1.10 2013/06/25 09:03:56 ragarwal Exp $
#
#   Description : 
#     atcl utility to display sigem violations
#     Supports avg, peak, rms sigem violations
#
#   Usage:
#     atclDisplaySigem  -mode (avg | rms | peak) -min <> -max <> -color <> -res_dir <> 
#
#   Note: 
#     Script by default looks for adsRpt/SignalEM_Filtered folder. This can be changed by specifying res_dir arg. 
#     The SignalEM_Filtered folder is generated by  sigem post processing script. 
#
#   Last Modified $Date: 2013/06/25 09:03:56 $
# 
#   $Log: atclDisplaySigem.tcl,v $
#   Revision 1.10  2013/06/25 09:03:56  ragarwal
#
#   BugID:
#
#   Revision 1.8  2010/11/11 18:43:43  pritesh
#   *** empty log message ***
#
#   Revision 1.7  2010/10/28 17:28:55  pritesh
#   Update for showing user specified number of worst violations.
#   The output worst violation report changed from Worst10Sigem.list to WorstSigem.list
#   The default value for worst violations is 10, and 0 turns off the worst violations (show all)
#
#   Revision 1.6  2010/10/28 04:06:57  pritesh
#   Added info to report to terminal
#
#   Revision 1.5  2010/10/28 03:57:30  pritesh
#   Updated net name handling
#
#   Revision 1.4  2010/10/27 19:00:08  pritesh
#   Worst10Sigem.list report generated for the case when showworst =1
#
#   Revision 1.3  2010/10/27 18:44:31  pritesh
#   Updates:
#    1. Added functionality to show worst 10 sigem violations for avg/rms/peak mode
#    2. Added functionality to show the sigem violations for the specified net only
#    3. Added functionality to show connected instances for the specified net
#    4. Color palette updated: # violations in each color range also printed
#    5. Output files generated: ShowSigemNets.cmd
#
#   Revision 1.2  2010/10/27 00:40:08  pritesh
#   man page update
#
#   Revision 1.1  2010/10/27 00:20:21  pritesh
#   Initial Check-in
#
###############################################################

proc atclTemplate_manpage {} {
  puts "

    SYNOPSIS
      Displays sigem violations in RedHawk GUI  (for avg, peak, rms mode)

    DESCRIPTION
      atclDisplaySigem.tcl
      -res_dir  <sigem results directory> (Default: adsRpt/SignalEM_Filtered/) 
      -mode     \[avg \| rms \| peak\]  (Default: rms) 
      -min      <lowest_violation%> (Default: 0)
      -max      <highest_violaiton%> (Default: All)
      -color    <Red|Green|Blue|Yellow|Orange|White|Purple|Gradient> (Default: Gradient)
      -showworst \[0\|<val>\] (Default: 10) Display worst <val> sigem violations only. 0 means show all violations.
      -net      <net_name> Display sigem violations for this net only
      -conninst \[0\|1\]  (Default: 1) (Combine with -net) Show connected instances to net (-net) (Driver shown as white)
      -width    <Width 1(lighter)-10(stronger)>  
      -man  1   man page
      -help 1   help 

      Example:
        atclDisplaySigem -min 0 -max 100 -mode avg 
"
}

proc atclTemplate_help {} {
  puts "Usage: atclDisplaySigem -mode \[avg\|rms\|peak\] \[ -min <val%> -max <val%> | -net <net_name> -conninst <0|1> \] -color <val> -width <val> -res_dir <sigem_result_dir> -showworst"
  puts "type atclDisplaySigem -man 1 for command synopsys" 
}

global lim
proc atclDisplaySigem { args } {

  array set opt [concat {-res_dir "./adsRpt/SignalEM_Filtered/" -mode "rms"  -min 0 -max 0  -color "Gradient" -net 0 -conninst 1 -width 3 -showworst 10 -h 0 -help 0 -man 0 } $args ] 
  set res_dir $opt(-res_dir)
  set mode $opt(-mode)
  set color $opt(-color)
  set min $opt(-min)
  set max $opt(-max)
  set net $opt(-net)
  set conninst $opt(-conninst)
  set showworstcnt $opt(-showworst)
  set width $opt(-width)
  set help $opt(-help) 
  set help $opt(-h) 
  set man $opt(-man) 
  
  if { $man==1 }  { 
    atclTemplate_manpage 
    return 
  } 
  
  if { $help==1 }  { 
    atclTemplate_help 
    return 
  }

  
  set a [config cmdlog off]
  
  puts "SignalEM Violation Display" 
  puts "Mode: $mode" 

  puts "Reading input data from $res_dir"                       
  set design [ get design ]  
  set emfile "$res_dir/$design.$mode\_em.worst"
  
  set fp [open ".tmp.em.sh" w]
  set fp1 [open ".tmp.nets.out" w]
  
  set a [ config viewnet -name all -mode off ] 
  set a [ config viewlayer -name metalonly -style fill ]
  set a [ plot line -clear ] 
  set a [ select clearall ] 
  set min1 $min 
  set worst "" 
  if { $showworstcnt == 0 } { 
     set showworst 0 
  } else { 
     set a [ string is integer -strict $showworstcnt ] 
     if { $a == 0 } { 
       puts "Invalid value for -showworst. Expected integer"
       puts "Using default value (10 worst sigem violations)" 
       set showworstcnt 10 
       set showworst 1 
     } else { 
       set showworst 1 
     }
  }
  if { $showworst == 1 } {
    set worst "\| head -$showworstcnt"
    puts "Showing worst $showworstcnt  sigem violations only"
    puts "Specify -showworst 0 to turn off this feature"
    set wrst [open ".tmp.worst" w]
  }
  if { $net != 0 } { 
    puts "Displaying net: $net"
    puts $fp "grep $net $emfile | grep -v \^via | awk -F \\% \'\{print \$1\}\'  | awk -F \\( \'\{print \$2\}\' | awk -F \\) \'\{print \$1\,\$2\}\' | awk -F \\, \'\{print \$1 \, \$2\, \$3\}\' $worst"   
    if { $showworst == 1 } { 
      puts $fp1 "grep $net $emfile | awk \'\{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' $worst"  
      puts $wrst "grep $net $emfile | grep -v \^via $worst" 
    } else { 
      puts $fp1 "grep $net $emfile | awk \'\{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' | sort -u $worst"  
    }
  } elseif { $max == 0 }  { 
    puts "Displaying nets with sigem violations range: ($min to All)"
    puts $fp "grep -v \^\$ $emfile | grep -v \^\# | grep -v \^via | awk -F \\% \'\{print \$1\}\'  | awk \'\(\$4 > $min\) \{print\}\' | awk -F \\( \'\{print \$2\}\' | awk -F \\) \'\{print \$1\,\$2\}\' | awk -F \\, \'\{print \$1 \, \$2\, \$3\}\' $worst"   
    if { $showworst == 1 } { 
      puts $fp1 "grep -v \^via $emfile |  awk -F \\% \'\{print \$1\, \$2\}\'  | awk \'\(\$4 > $min\) \{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' $worst"  
      puts $wrst "grep -v \^\$ $emfile | grep -v \^\# | grep -v \^via $worst"   
    } else { 
      puts $fp1 "grep -v \^via $emfile |  awk -F \\% \'\{print \$1\, \$2\}\'  | awk \'\(\$4 > $min\) \{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' | sort -u $worst"  
    } 
  } elseif {$min == $max}  { 
    puts "Displaying nets with violation $min "
    puts $fp "grep -v \^\$ $emfile | grep -v \^\# | grep -v \^via |  awk -F \\% \'\{print \$1\}\'  | awk \'\(\$4==$min\) \{print\}\' | awk -F \\( \'\{print \$2\}\' | awk -F \\) \'\{print \$1\,\$2\}\' | awk -F \\, \'\{print \$1 \, \$2\, \$3\}\' $worst"  
    if { $showworst == 1 } { 
      puts $fp1 "grep -v \^via $emfile |  awk -F \\% \'\{print \$1\, \$2\}\'  | awk \'\(\$4==$min\) \{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' $worst"  
      puts $wrst "grep -v \^\$ $emfile | grep -v \^\# | grep -v \^via $worst"  
    } else { 
      puts $fp1 "grep -v \^via $emfile |  awk -F \\% \'\{print \$1\, \$2\}\'  | awk \'\(\$4==$min\) \{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' | sort -u $worst"  
    } 
  } else { 
    puts "Displaying nets with sigem violations range: ($min to $max)"
    puts $fp "grep -v \^\$ $emfile | grep -v \^\# | grep -v \^via  |  awk -F \\% \'\{print \$1\}\'  | awk \'\(\(\$4>$min\) \&\& \(\$4 < $max\)\) \{print\}\' | awk -F \\( \'\{print \$2\}\' | awk -F \\) \'\{print \$1\,\$2\}\' | awk -F \\, \'\{print \$1 \, \$2\, \$3\}\' $worst"  
    if { $showworst == 1 } { 
      puts $fp1 "grep -v \^via $emfile |  awk -F \\% \'\{print \$1\, \$2\}\'  |awk \'\(\(\$4>$min\) \&\& \(\$4 < $max\)\) \{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' $worst"  
      puts $wrst "grep -v \^\$ $emfile | grep -v \^\# | grep -v \^via $worst"  
    } else { 
      puts $fp1 "grep -v \^via $emfile |  awk -F \\% \'\{print \$1\, \$2\}\'  |awk \'\(\(\$4>$min\) \&\& \(\$4 < $max\)\) \{print \"config viewnet -name \{\" \$5 \"\} -mode on\"\}\' | sort -u $worst"  
    }
  } 
  close $fp
  close $fp1 

  if {$showworst ==1 } { 
    close $wrst 
    if { [ catch { set my_line [ exec bash .tmp.worst ] } ] == 0 } {
      set fp1 [ open "WorstSigem.list" w ]
      puts $fp1 "#Generated by atclDisplaySigem.tcl" 
      puts $fp1 "#Mode: $mode"
      if { $my_line != "" } { 
        puts $fp1 $my_line 
      }
      close $fp1 
      exec rm .tmp.worst
    } else { 
      puts "error"
    }
  }
    
  if { [ catch { set my_line [ exec bash .tmp.em.sh ] } ] == 0 } {
    set fp1 [ open ".tmp.sorted.out" w ]
    if { $my_line != "" } { 
      puts $fp1 $my_line 
    }
    close $fp1 
  } else { 
    puts "error"
  }
  
  if { [ catch { set my_line [ exec bash .tmp.nets.out] } ] == 0 } {
    set fp1 [ open ".tmp.nets.out.cmd" w ] 
    if { $my_line != "" } { 
      puts $fp1 $my_line 
    }
    if { $net !=0 &&  $conninst == 1 }  { 
      puts $fp1 "select add \[ get instbynet $net \] -color yellow"
      puts $fp1 "select add \[ get instbynet $net -driver \] -color white -linewidth 2"
      set driver [ get instbynet $net -driver ] 
      puts "Net Driver: $driver"
    }
    close $fp1 
  } else { 
    puts "error"
  }
  
  set a [ source .tmp.nets.out.cmd ] 

  set fp [ open ".tmp.sorted.out" r ] 
  set cnt 0 
  set min 0 
  set max 0 
  set line "" 
  while {[gets $fp line ]>= 0} { 
    if { $cnt == 0 } { 
      set max [ lindex $line 4 ]  
    }
    incr cnt
    set min [ lindex $line 4 ] 
    set x1 [ lindex $line 0 ] 
    set y1 [ lindex $line 1 ] 
    set x2 [ lindex $line 2 ] 
    set y2 [ lindex $line 3 ] 
    set seg($min) "$x1 $y1 $x2 $y2" 
  }
  close $fp 
  
  if { $cnt == 0 } { 
    if { $net != 0 } { 
      puts "No matching violation for net $net found"
    } else { 
      puts "No matching violation in the specified range found"
    }
    return
  }
  
  set fp [ open "ShowSigemNets.cmd" w ] 
  set step 0 
  global lim
  if { $color == "Gradient" } { 
   set min2 $min 
   if { $min1 != 0 } { 
     set min $min1   
   }
   set step [ expr ($max - $min)/6 ]
   set a [ create_limit $min $step ] 
   set clrcnt(Red) 0 
   set clrcnt(Orange) 0 
   set clrcnt(Yellow) 0 
   set clrcnt(Green) 0 
   set clrcnt(Blue) 0 
   set clrcnt(Purple) 0 
   
   foreach viol [ array names seg ] { 
     set clr  [ get_color $viol $min $max $step]
     puts $fp "plot line -position $seg($viol) -color $clr -width $width"
     incr clrcnt($clr)
   }
   set min [ format "%.3f"  $min  ]  
   puts "Min Violation:  $min2"
   puts "Max Violation:  $max"
   puts "Total Violation:  $cnt"
   puts "Violation Color Palette:" 
   puts "------------------------------------------- " 
   puts "Color   :    Range               : #Viol    " 
   puts "------------------------------------------- " 
   puts [ format "%s: %s : %d" "Red     " "$lim(5) - $lim(4)" $clrcnt(Red) ]
   puts [ format "%s: %s : %d" "Orange" "$lim(4) - $lim(3)" $clrcnt(Orange) ]
   puts [ format "%s: %s : %d" "Yellow " "$lim(3) - $lim(2)" $clrcnt(Yellow) ]
   puts [ format "%s: %s : %d" "Green  " "$lim(2) - $lim(1)" $clrcnt(Green) ]
   puts [ format "%s: %s : %d" "Blue    " "$lim(1) - $lim(0)" $clrcnt(Blue) ]
   puts [ format "%s: %s : %d" "Purple " "$lim(0) - $min" $clrcnt(Purple) ]
   set rg [ open "sigem.color.range" w ] 
   puts $rg "atclDisplaySigem" 
   puts $rg "Mode: peak" 
   puts $rg "Min Violation:  $min2"
   puts $rg "Max Violation:  $max"
   puts $rg "Total Violation:  $cnt"
   puts $rg "Violation Color Range"
   puts $rg [ format "%s: %s: %d" "Red     " "$lim(5) - $lim(4)" $clrcnt(Red) ]
   puts $rg [ format "%s: %s: %d" "Orange" "$lim(4) - $lim(3)" $clrcnt(Orange) ]
   puts $rg [ format "%s: %s: %d" "Yellow " "$lim(3) - $lim(2)" $clrcnt(Yellow) ]
   puts $rg [ format "%s: %s: %d" "Green  " "$lim(2) - $lim(1)" $clrcnt(Green) ]
   puts $rg [ format "%s: %s: %d" "Blue    " "$lim(1) - $lim(0)" $clrcnt(Blue) ]
   puts $rg [ format "%s: %s: %d" "Purple " "$lim(0) - $min" $clrcnt(Purple) ]
   close $rg
  } else { 
   foreach viol [ array names seg ] { 
     puts $fp "plot line -position $seg($viol) -color $color -width $width"
   }
  }
  close $fp
 
  set a [ source ShowSigemNets.cmd ] 

  #exec rm .tmp.em.sh
  #exec rm .tmp.nets.out
  #exec rm .tmp.nets.out.cmd 
  #exec rm .tmp.sorted.out
  #exec rm ShowSigemNets.cmd
}


proc create_limit { min step } { 
  global lim
  set l1 [ format "%.3f" [ expr ( $step + $min ) ] ]  
  set lim(0) $l1 
  set l2 [ format "%.3f" [ expr ( $step*2 + $min ) ] ]  
  set lim(1) $l2
  set l3 [ format "%.3f" [ expr ( $step*3 + $min ) ] ]  
  set lim(2) $l3 
  set l4 [ format "%.3f" [ expr ( $step*4 + $min ) ] ]  
  set lim(3) $l4 
  set l5 [ format "%.3f" [ expr ( $step*5 + $min ) ] ]  
  set lim(4) $l5 
  set l6 [ format "%.3f" [ expr ( $step*6 + $min ) ] ]  
  set lim(5) $l6 
}

proc get_color { vl min max step }  {
  global lim
  global pur blue gre 
#  puts "$vl $min $max step $step " 
  
  if { $vl < $lim(0) } { 
    set clr1 "Purple"
  } elseif { $vl <= $lim(1) } {
    set clr1 "Blue"
  } elseif { $vl <= $lim(2) } {
    set clr1 "Green"
  } elseif { $vl <= $lim(3) } {
    set clr1 "Yellow"
  } elseif { $vl <= $lim(4) } {
    set clr1 "Orange"
  } elseif { $vl > $lim(4) } {
    set clr1 "Red"
  } else { 
    set clr1 "White"
  }
  return $clr1
}

