################################################################
# (C) COPYRIGHT 2010 Apache Design Systems
# ALL RIGHTS RESERVED
#
#
#   $Author: ragarwal $
#   $Date: 2013/06/25 09:04:45 $
#   $Revision: 1.16 $
#   $Id: atclSigemHisto.tcl,v 1.16 2013/06/25 09:04:45 ragarwal Exp $
#
#   Description : 
#     atcl utility to plot histogram  of sigem violations
#     Supports histogram for avg, peak, rms
#
#   Usage:
#     atclSigemHisto  -mode (avg | rms | peak) -min <> -max <> -bin_size <> -res_dir <> 
#
#   Note: 
#     Script by default looks for adsRpt/SignalEM folder. This can be changed by specifying res_dir arg. 
#     The SignalEM folder is generated by  sigem post processing script. 
#
#   Last Modified $Date: 2013/06/25 09:04:45 $
# 
#   $Log: atclSigemHisto.tcl,v $
#   Revision 1.16  2013/06/25 09:04:45  ragarwal
#
#   BugID:
#
#   Revision 1.14  2012/03/02 00:46:59  pritesh
#   - Changed the default result dir from adsRpt/SignalEM_Filtered to adsRpt/SignalEM
#     New signalEM flow does native result filtering. So script based filtering (which generates)
#     adsRpt/SignalEM_Filtered is not required.
#
#   Revision 1.12  2010/10/29 20:59:04  pritesh
#   updated temp file deletion
#
#   Revision 1.11  2010/10/29 20:21:50  pritesh
#   Updated intermediate file deletion. .*.hist will not be deleted.
#
#   Revision 1.10  2010/10/26 17:27:30  pritesh
#   clean up temp files
#
#   Revision 1.9  2010/10/26 17:18:24  pritesh
#   Update for Histogram to show name of map (em mode)
#
#   Revision 1.8  2010/10/21 22:59:45  pritesh
#   Multiple invocation of atclSigemHisto without closing the previous histograms is supported now.
#
#   Revision 1.7  2010/10/20 23:28:20  pritesh
#   Initial Check-in
#
###############################################################

proc atclTemplate_manpage {} {
  puts "

    SYNOPSIS
      Creates histogram of signal em violations  (for avg, peak, rms mode)

    DESCRIPTION
      atclSigemHisto.tcl
      -res_dir  <sigem results directory> (Default: adsRpt/SignalEM/) 
      -mode     \[avg \| rms \| peak\]  (Default: rms) 
      -min      <lowest_violation%> (Default: 0)
      -max      <highest_violaiton%> (Default: All)
      -bin_size <volts> (Default: 10%)
      -man  1   man page
      -help 1   help 

      Example:
        atclSigemHisto -bin_size 10 -min 0 -max 100 -mode avg 
"
}

proc atclTemplate_help {} {
  puts "Usage: atclSigemHisto -mode \[avg\|rms\|peak\] -min <val%> -max <val%> -bin_size <val> -res_dir <sigem_result_dir>"
  puts "type atclSigemHisto -man 1 for command synopsys" 
}

proc atclSigemHisto { args } {

  array set opt [concat {-res_dir "./adsRpt/SignalEM/" -mode "rms"  -min 0 -max 0  -bin_size 10 -h 0 -help 0 -man 0 } $args ] 
  set res_dir $opt(-res_dir)
  set mode $opt(-mode)
  set bin_size $opt(-bin_size)
  set min $opt(-min)
  set max $opt(-max)
  set help $opt(-help) 
  set help $opt(-h) 
  set man $opt(-man) 
  
  if { $man==1 }  { 
    atclTemplate_manpage 
    return 
  } 
  
  if { $help==1 }  { 
    atclTemplate_help 
    return 
  } 
  set a [config cmdlog off]
  puts "SignalEM Histogram Generation" 
  puts "Mode: $mode" 
  if { $max == 0 }  { 
    puts "Min: $min ; Max: All ; bin_size: $bin_size"
  } else { 
    puts "Min: $min ; Max: $max ; bin_size: $bin_size"
  }
  puts "Reading input data from $res_dir"                       
  
  set design [ get design ]  
  #set emfile "$res_dir/$design.$mode\_em.worst"
  set emfile "$res_dir/$design.em.worst.$mode"
  global env 
  set aroot "$::env(APACHEROOT)"
  set mode [ string toupper $mode ]   
  if { [ file  exists $emfile ] } {
      #if { [ file exists ".tmp.em1" ] } { 
      #  exec \rm .tmp.em1
      #}
      set fp [open ".tmp.em.sh" w]
      puts $fp "grep -v \^\# $emfile | grep -v \^\$ | awk \'\{ print \$4\}\' | awk -F \\\% \'\{print \$1\}\'"  
      close $fp
      if { [ catch { set my_line [ exec bash .tmp.em.sh ] } ] == 0 } {
         set fp1 [ open ".$mode\_SIGEM_VIOLATION" w ] 
         puts $fp1 $my_line 
         close $fp1 
      } else { 
         puts "erorr"
      }
      exec rm .tmp.em.sh 
      if { $max == 0 } { 
        exec perl $aroot/scripts/genHisto.pl -min_vol $min -bin_size $bin_size -rep .$mode\_SIGEM_VIOLATION -field 0 &
      } else { 
        exec perl $aroot/scripts/genHisto.pl -min_vol $min -max_vol $max -bin_size $bin_size -rep .$mode\_SIGEM_VIOLATION -field 0 & 
      }
  } else { 
    puts "-ERROR- cannot read $emfile " 
  }
  
  exec rm .$mode\_SIGEM_VIOLATION 
# exec rm .$mode\_SIGEM_VIOLATION.hist
}
 
 
