#Specify the APL run mode, design dependent or design independent
APL_RUN_MODE DI

#Specify the LEF files
LEF_FILES {
    ../../data/lef/scc40nll_vhsc40_hvt_ant.lef
}

# #Specify .lib files
# LIB_FILES {
#     /nfs/apl1/user_data/lib/IO.lib
#     /nfs/apl1/user_data/lib/ANALOG.lib
# }



#Specify Spice subckt netlist file
SPICE_SUBCKT {
    ../../data/cdl/scc40nll_vhsc40_hvt.cdl
}


#Nominal Vdd value
VDD 1.1

#Vdd names
VDD_NAME VDD

#Ground names
GND_NAME VSS


PRIMARY_VDD_PIN VDD

PRIMARY_GND_PIN VSS

# DC VNW VDD

# DC VPW 0

#Define design corner
DESIGN_CORNER {
    # 最大动态功耗
    ff1p21v125c {
        TEMP 125
        PROCESS FF
        VDD 1.21
        DEVICE_MODEL_LIBRARY ../../data/models/SMIC_SP_model_40LL_1125_V1.15/hspice/l0040ll_v1p15.lib FF
        LIB_FILES {
            /mnt/hgfs/Em/40NM/S40/smic/SCC40NLL_VHSC40_HVT_V0.1/SCC40NLL_VHSC40_HVT_V0p1/liberty/1.1v/scc40nll_vhsc40_hvt_ff_v1p21_125c_ccs.lib
            }
    }
    # 最大漏功耗
    ss0p99vm40c {
        TEMP -40
        PROCESS SS
        VDD 0.99
        DEVICE_MODEL_LIBRARY ../../data/models/SMIC_SP_model_40LL_1125_V1.15/hspice/l0040ll_v1p15.lib SS
        LIB_FILES {
            /mnt/hgfs/Em/40NM/S40/smic/SCC40NLL_VHSC40_HVT_V0.1/SCC40NLL_VHSC40_HVT_V0p1/liberty/1.1v/scc40nll_vhsc40_hvt_ss_v0p99_-40c_ccs.lib
            }
    }
}

DEBUG 1

#（报错出现lib相关的时候设置）
#ENHANCED_LIB_SUPPORT 1 

#Specify the maximum number of simultaneous jobs
JOB_COUNT 20

#Specify the transistor dimension scale factor
SIZE_SCALE 0.9

#Specify your working directory
WORKING_DIR ./working

#Specify the directory for temporary working files
TMP_DIR ./temp

APL_RESULT_DIRECTORY ./cellresults

SIMULATOR_COMMAND_OPTION -include_last ./option.sp


# 使用HSPICE仿真更精确
APL_HSPICE /export/SoftWare/Synopsys/hspice/T-2022.06-1/hspice/bin/hspice

# APL_SPECTRE /export/SoftWare/Cadence/SPECTRE21.10.582/bin/spectre
