eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}'
  && eval 'exec perl -S $0 $argv:q'
  if 0;
$author = "
For issues/questions please contact

Karan Sahni 
Email: karan\@apache-da.com 
Apache Design Solutions Inc.
San Jose,CA
\n" ;
$version = "Version 5.0";

$help =" 
Script to run CPM + Package Transient Analysis 
Please Refer to usage of the script using -u switch 	
\n\n";

$rev_history = "
\n";


#----------------------------------------------------------------------------------------------------------------------

$usage = " 
Detailed Usage of the Script


USAGE  :  ./cpm_pkg_analysis.pl 
				-p <ploc file> 
				-c <CPM of the design> 
				-s <pkg spice netlist> 
				-t <total simulation time including presim> 
				-d <time step> 
				
				-h <quick help>
				-u <detail usage> 

OUTPUT:\n    
	  correlation.sp (Spice Deck for Transient Analysis)
	  
	  Script runs NSPICE on this file to create correlation.ta0 which has the Transient Simulation Output.
	  Please refer to the file ./log.lis for spice run check
	  
	  Script also executes the Apache Signal Viewer which helps to view the Spice Waveforms.
	  For a correlation for Spice to RedHawk waveforms , user will need to shift the RedHawk waveforms
	  by a time equal to Presim Time used in the RedHawk simulation.
	  This is to offset the -ve time scale (used for presim in RedHawk).  



NOTE : ** Please make sure to cross check the Spice Deck Generated by the script for authentication of the results** 
	  
\n";


use Getopt::Std;
getopts("vhup:c:s:t:d:");

if($opt_h) { print "$rev_history\n$version\n$author\n"; exit(0);}
if($opt_v) { print "Latest version of $path = $version\n$author\n"; exit(0);}
if($opt_u) { print "\n\n$usage\n$author\n$path\n"; exit(0);}

#--------------------------------------------------------------------

if( !(($opt_h || $opt_v || $opt_u) || ($opt_p && $opt_c && $opt_s && $opt_t && $opt_d))) {
    print "ERROR :: Please refer to usage: \n$usage\n\n";
    exit(0);
}

$source1 = $opt_p;
$source2 = $opt_c;
$source3 = $opt_s;
$sim_time = $opt_t;
$time_step = $opt_d;

###############################################
####  MAIN PROGRAM STARTS HERE ################
###############################################

open (pkg,">pkg_data.txt");
open (cpm,">cpm_data.txt");


##########################
### PARSING PLOC FILE ####
##########################


open (F1,"$source1") || die "Cound not open file $source1 for reading\n";
while (<F1>) {
    if (/^\s*#/) { next; }
    	if (/(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/) {
        $ploc=$1; $x_cor=$2; $y_cor=$3; $metal=$4; $domain=$5; $pkg_port=$6;
		$package_ploc{$ploc} = $pkg_port;
	}
}
close F1;


###################################
### PARSING CPP HEADER FROM CPM ###
###################################

$cpm_cpp_start=0;
open (F2,"$source2") || die "Could not open file $source2 for reading\n";
while (<F2>) {
	$temp= $_;
    $line = $_;

for ($line) {
s/^\s+//;
}

@_=$line;
split ;

$first=$_[0];
$second =$_[1];

if($first eq "*" && $second eq "Begin"){
		  $cpm_cpp_start= 1;
print "\n Started Processing CPP header from CPM to map DIE pads to CPM ports \n\n\n\n";

		while ($line !~ /^\* End/){
			print cpm ("$line");
			$line = <F2>;
		}
}
}
if ($cpm_cpp_start == 0){
	print ("\n\nFATAL ERRROR [1] CPM Does not contain a valid Chip Package Protocol Header\n\n");
	exit(0);

}

close $F2;
system `dos2unix cpm_data.txt`;

#####################################
### PARSING PACKAGE SPCIE NETLIST ###
#####################################


$rh_pkg_found = 0;
open (F3,"$source3") || die "Cound not open file $source3 for reading\n";
while (<F3>) {
    	$temp= $_;
        $line = $_;

for ($line) {
s/^\s+//;
}

@_=$line;
split ;

$first= $_[0];
$second = $_[1];
$third = $_[2];

	if ($first =~ m/.subckt/ && $second =~ m/redhawk_pkg/i && $third eq '') {
		$r_pkg = $second ;
		$line = <F3>;
		print "\n RedHawk package spice SUB-CIRCUIT found \n\n\n\n";
		$rh_pkg_found = 1;
				while ($line !~ m/^x|^v|^ x|^ v|^  x|^  v/i) {
					print pkg ("$line");
					$line = <F3>;

				}
	


	}
}
if ($rh_pkg_found  == 0){
	print ("\n\nFATAL ERROR [2] :Package Model  Does not contain a valid RedHawk Subckt , please use Package Compiler to Sanity check the packge model \n");
	exit (0);
}

close $F3;
close $pkg;
close $cpm;

system `dos2unix pkg_data.txt`;

################################
### GET CPM to PLOC MAPPING ####
################################

open (temp,"cpm_data.txt") || die " Could not open cpm_data.txt , check if CPP header in CPM is correct";

while (<temp>){
	if (/^\s*#/) { next; }
	if (/^(\s)*$/) { next; }
        

	chomp;
	split;		

	$ploc=$_[1]; 
	$cpm_port=$_[6];
	if (defined $ploc && defined $cpm_port){
	$cpm_port_hash{$ploc} = $cpm_port;
	}
}
close $temp;

#######################################################################



####################################################
### GENERATE SPICE DECK FOR TRANSIENT ANALYSIS #####
####################################################


#### Main Spice parameters definition ####
open (tran,">correlation.sp");
print tran ("* This Spice Deck Can be Used for CPM + Pkg transient simulation\n\n");
print tran ("* Spice Keywords for Fixed Time Step and Euler Integration\n");
print tran (".option BANDLIM = 1\n");
print tran (".option MAXORD =1\n");
print tran (".option MAXISRC =100\n");
print tran (".option BLSN \n");
print tran (".option FIXTSTEP = 1\n\n\n\n\n");


################### MAIN CPM SUBCKT INSTANTIATION ################

print tran ("* Full circuit instantiation CPM + Package\n"); 
print tran ("Xcpm  ");
open (main,"$source1");
print tran ("\n+ ");
while (<main>) {
	if (/^\s*#/) { next; }
	if($_ =~ /^$/) { next;}

	chomp;
	split;

	$ploc =$_[0];
	$temp = $cpm_port_hash{$ploc};
	$sort_cpm{$temp} = 1;
	}
foreach $mykeys (sort keys %sort_cpm){
	print tran ("$mykeys","  "); 
}
close $main;

print tran ("\n");
open (pkgsub2,"pkg_data.txt");
while (<pkgsub2>) {
	$ports = $_;
	if (/^(\s)*$/) { next; }
	print tran ("$ports"); 
}
close $pkgsub2;

print tran ("+ cpm");
print tran ("\n\n");

################## Main CPM Subckt Ends Here ###########################

## Resistor to short CPM + Pkg Ports ###
print tran ("* Zero Ohm resistors to short CPM ports to Die side Package Ports\n");

open (pad,"$source1");
while (<pad>) {
	if (/^\s*#/) { next; }
	if (/^(\s)*$/) { next; }


		chomp;
		split;

		$ploc =$_[0];
			if (defined $ploc) {
			print tran ("R_$ploc","\t","$cpm_port_hash{$ploc}_out","\t",$package_ploc{$ploc},"\t","0","\n"); 
			}
}
close $pad;
print tran ("\n\n\n\n");

## Resistor to create current probing for each port
print tran ("*Resistor to create Current probing point for each CPM port\n"); 
open (resi,"$source1");
while (<resi>) {
	if (/^\s*#/) { next; }
	if (/^(\s)*$/) { next; }

	chomp;
	split;

	$ploc =$_[0];
	if (defined $ploc && defined $cpm_port_hash{$ploc}){
	$temp = $cpm_port_hash{$ploc};
	$sort_cpm{$temp} = 1;
	}

}
foreach $mykeys ( sort keys %sort_cpm){
	if (defined $mykeys){
	print tran ("R$mykeys","\t","$mykeys","\t",$mykeys,"_out","\t","0","\n"); 
	}
}
close $resi;
print tran ("\n\n");


### Transient Analysis Settings ###

print tran ("*Transient analysis settings\n"); 
print tran (".tran"," ", "$time_step","ps"," ", "$sim_time", "ns"," ", "START=0","\n\n");

### Probe Generation for Current and Voltage ###

print tran ("* Current Probe on Each Pad on the DIE\n");

## Probe Current
open (probei,"$source1");
while (<probei>) {
	if (/^\s*#/) { next; }
	if (/^(\s)*$/) { next; }

	chomp;
	split;

	$ploc =$_[0];
	if (defined $ploc && defined $cpm_port_hash{$ploc}){
	$temp = $cpm_port_hash{$ploc};
	$sort_cpm{$temp} = 1;
	}

}
foreach $mykeys ( sort keys %sort_cpm){
	if (defined $mykeys){
	print tran (".probe  i(R$mykeys)","\n"); 
	}
}
close $probei;
print tran ("\n\n");

## probe voltage
print tran ("* Voltage Probe on each CPM port\n"); 
open (probev,"$source1");
#open (karan,">karan.txt");
while (<probev>) {
	$line= $_;
	if (/^\s*#/) { next; }
	if (/^(\s)*$/) { next; }
        
#	print karan ("$line");
	
	chomp;
	split;

	$ploc =$_[0];
	if (defined $ploc && defined $cpm_port_hash{$ploc}){
	$temp = $cpm_port_hash{$ploc};
	$sort_cpm{$temp} = 1;
	}

}
foreach $mykeys ( sort keys %sort_cpm){
	if (defined $mykeys){
	print tran (".probe  v($mykeys)","\n"); 
	}
}
close $probev;
print tran ("\n\n");

###############################

### Subckt CPM ###

### Building Baisc CPM subckt which brings in Package and DIE Ports  ######

print tran ("* Instantiation of CPM + PKG  \n");
print tran (".subckt cpm  ");
open (cpmmain,"$source1");
while (<cpmmain>) {
	if (/^\s*#/) { next; }

	chomp;
	split;

	$ploc =$_[0];
	$temp = $cpm_port_hash{$ploc};
	$sort_cpm{$temp} = 1;
}
close $probev;
print tran ("\n+ ");
foreach $mykeys (sort keys %sort_cpm){
	print tran ("$mykeys","  "); 
}
close $cpmmain;

print tran ("\n");

open (pkgsub1,"pkg_data.txt");
while (<pkgsub1>) {
	$ports = $_;
	if (/^(\s)*$/) { next; }
	print tran ("$ports"); 
}
close $pkgsub1;

print tran ("\n\n");

############################################

print tran (".include   '$source2'\n");
print tran (".include   '$source3'\n\n");


## CPM instantiation from adsPowermodel Subckt ####
open (cpms,">cpm_sub.txt");
open (cpmsub,"$source2");

while (<cpmsub>) {
	$cpmports = $_;
	split ;

$firstc = $_[0];
$secondc = $_[1];
$thirdc = $_[2];

	if ($firstc =~ m/.subckt/ && $secondc =~ m/adsPowermodel/i && $thirdc eq '') {
		$cpmports = <cpmsub>;
		print "\n CPM  spice SUB-CIRCUIT found \n\n\n\n";
				
				while ($cpmports !~  m/^x/i) {
						print cpms ("$cpmports");
						$cpmports = <cpmsub>;

				}

	}

	
}
close $cpmsub;
close $cpms;
system `dos2unix cpm_sub.txt`;

open (cpmint,"cpm_sub.txt");
print tran ("Xpwrmodel\n");

while (<cpmint>) {
	$nodes = $_;
	if (/^(\s)*$/) { next; }
	print tran ("$nodes"); 
}
close $cpmint;

print tran ("+ adsPowermodel\n\n");

#### Package Instantiation from RLCK Package Model ####

open (pkgsub,"pkg_data.txt");
print tran ("Xpkg\n");

while (<pkgsub>) {
	$ports = $_;
	if (/^(\s)*$/) { next; }
	print tran ("$ports"); 
}
close $pkgsub;

print tran ("+ $r_pkg\n");
print tran (".ends\n");
print tran ("\n\n\n\n");

###########################################################################
close $tran;
print (" SPICE deck for transient analysis completed , the file is correlation.sp \n\n\n\n");

system `rm -rf cpm_data.txt  cpm_sub.txt pkg_data.txt`;
print (" \n\n\n**************** SPICE SIMULATION STARTED ***********************\n\n\n");
system   `nspice correlation.sp -o log.lis &`;
system   `sv correlation.ta0 &`;
exit;
